volumes:
  data_db:

services:
  postgres:
    image: postgres-14:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123