volumes:
  data_db:

services:
  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=246357
      - POSTGRES_DB=aspire-lite
  migrate:
    image: migrate/migrate
    volumes:
        - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://tester:246357@postgres:5432/aspire-lite?sslmode=disable", "up", "3"]
    depends_on:
      - postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - db_host=postgres
    depends_on:
      - postgres
    command: [ "/app/main" ]